// <auto-generated />
using System;
using BusMap.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusMap.WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<TimeSpan>("Hour");

                    b.Property<string>("Label")
                        .HasMaxLength(50);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("RouteId");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("BusStops");

                    b.HasData(
                        new { Id = 1, Address = "Gorlice", Hour = new TimeSpan(0, 10, 0, 0, 0), Label = "Gorlice DA", Latitude = 49.662932, Longitude = 21.159447, RouteId = 1 },
                        new { Id = 2, Address = "Jasło", Hour = new TimeSpan(0, 10, 20, 0, 0), Label = "Jasło DA", Latitude = 49.74375, Longitude = 21.473399, RouteId = 1 },
                        new { Id = 3, Address = "Frysztak", Hour = new TimeSpan(0, 10, 30, 0, 0), Latitude = 49.84548, Longitude = 21.612531, RouteId = 1 },
                        new { Id = 4, Address = "Wiśniowa", Hour = new TimeSpan(0, 10, 40, 0, 0), Latitude = 49.869611, Longitude = 21.65995, RouteId = 1 },
                        new { Id = 5, Address = "Dobrzechów", Hour = new TimeSpan(0, 10, 50, 0, 0), Latitude = 49.876198, Longitude = 21.75399, RouteId = 1 },
                        new { Id = 6, Address = "Strzyżów", Hour = new TimeSpan(0, 11, 0, 0, 0), Label = "Strzyżów DA", Latitude = 49.869992, Longitude = 21.800657, RouteId = 1 },
                        new { Id = 7, Address = "Czudec", Hour = new TimeSpan(0, 11, 10, 0, 0), Label = "Czudec DA", Latitude = 49.945855, Longitude = 21.837562, RouteId = 1 },
                        new { Id = 8, Address = "Boguchwała", Hour = new TimeSpan(0, 11, 20, 0, 0), Latitude = 49.983775, Longitude = 21.942793, RouteId = 1 },
                        new { Id = 9, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 30, 0, 0), Label = "Podkarpacka", Latitude = 50.020076, Longitude = 21.980312, RouteId = 1 },
                        new { Id = 10, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 40, 0, 0), Label = "Rzeszów DA", Latitude = 50.042131, Longitude = 22.003429, RouteId = 1 },
                        new { Id = 11, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 50, 0, 0), Label = "Rejtana", Latitude = 50.031346, Longitude = 22.016653, RouteId = 1 },
                        new { Id = 12, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 0, 0, 0), Label = "Rejtana", Latitude = 50.030767, Longitude = 22.017088, RouteId = 2 },
                        new { Id = 13, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 10, 0, 0), Label = "Rzeszów DA", Latitude = 50.042131, Longitude = 22.003429, RouteId = 2 },
                        new { Id = 14, Address = "Rzeszów", Hour = new TimeSpan(0, 11, 20, 0, 0), Label = "Podkarpacka", Latitude = 50.020076, Longitude = 21.980312, RouteId = 2 },
                        new { Id = 15, Address = "Boguchwała", Hour = new TimeSpan(0, 11, 30, 0, 0), Latitude = 49.983775, Longitude = 21.942793, RouteId = 2 },
                        new { Id = 16, Address = "Czudec", Hour = new TimeSpan(0, 11, 40, 0, 0), Label = "Czudec DA", Latitude = 49.945855, Longitude = 21.837562, RouteId = 2 },
                        new { Id = 17, Address = "Strzyżów", Hour = new TimeSpan(0, 11, 50, 0, 0), Label = "Strzyżów DA", Latitude = 49.869992, Longitude = 21.800657, RouteId = 2 },
                        new { Id = 18, Address = "Dobrzechów", Hour = new TimeSpan(0, 12, 0, 0, 0), Latitude = 49.876198, Longitude = 21.75399, RouteId = 2 },
                        new { Id = 19, Address = "Wiśniowa", Hour = new TimeSpan(0, 12, 10, 0, 0), Latitude = 49.869611, Longitude = 21.65995, RouteId = 2 },
                        new { Id = 20, Address = "Frysztak", Hour = new TimeSpan(0, 12, 20, 0, 0), Latitude = 49.84548, Longitude = 21.612531, RouteId = 2 },
                        new { Id = 21, Address = "Jasło", Hour = new TimeSpan(0, 12, 30, 0, 0), Label = "Jasło DA", Latitude = 49.74375, Longitude = 21.473399, RouteId = 2 },
                        new { Id = 22, Address = "Gorlice", Hour = new TimeSpan(0, 12, 40, 0, 0), Label = "Gorlice DA", Latitude = 49.662932, Longitude = 21.159447, RouteId = 2 },
                        new { Id = 23, Address = "Frysztak", Hour = new TimeSpan(0, 8, 0, 0, 0), Latitude = 49.84548, Longitude = 21.612531, RouteId = 3 },
                        new { Id = 24, Address = "Wiśniowa", Hour = new TimeSpan(0, 8, 10, 0, 0), Latitude = 49.869611, Longitude = 21.65995, RouteId = 3 },
                        new { Id = 25, Address = "Dobrzechów", Hour = new TimeSpan(0, 8, 20, 0, 0), Latitude = 49.876198, Longitude = 21.75399, RouteId = 3 },
                        new { Id = 26, Address = "Strzyżów", Hour = new TimeSpan(0, 8, 30, 0, 0), Label = "Strzyżów DA", Latitude = 49.869992, Longitude = 21.800657, RouteId = 3 },
                        new { Id = 27, Address = "Zaborów", Hour = new TimeSpan(0, 8, 40, 0, 0), Latitude = 49.914127, Longitude = 21.827073, RouteId = 3 },
                        new { Id = 28, Address = "Czudec", Hour = new TimeSpan(0, 8, 50, 0, 0), Label = "Czudec DA", Latitude = 49.945855, Longitude = 21.837562, RouteId = 3 },
                        new { Id = 29, Address = "Boguchwała", Hour = new TimeSpan(0, 9, 0, 0, 0), Latitude = 49.983775, Longitude = 21.942793, RouteId = 3 },
                        new { Id = 30, Address = "Rzeszów", Hour = new TimeSpan(0, 9, 10, 0, 0), Label = "Podkarpacka", Latitude = 50.020076, Longitude = 21.980312, RouteId = 3 },
                        new { Id = 31, Address = "Rzeszów", Hour = new TimeSpan(0, 9, 20, 0, 0), Label = "Rzeszów DA", Latitude = 50.042131, Longitude = 22.003429, RouteId = 3 }
                    );
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStopQueued", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<TimeSpan>("Hour");

                    b.Property<string>("Label")
                        .HasMaxLength(50);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("RouteQueuedId");

                    b.HasKey("Id");

                    b.HasIndex("RouteQueuedId");

                    b.ToTable("BusStopsQueued");
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStopTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusStopId");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("FORMAT(GetDate(), 'yyyy-MM-dd')");

                    b.Property<TimeSpan>("Hour")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("Format(GETDATE(),'hh:mm')");

                    b.HasKey("Id");

                    b.HasIndex("BusStopId");

                    b.ToTable("BusStopTraces");

                    b.HasData(
                        new { Id = 1, BusStopId = 1, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 5, 0, 0) },
                        new { Id = 2, BusStopId = 1, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 13, 0, 0) },
                        new { Id = 3, BusStopId = 1, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 9, 0, 0) },
                        new { Id = 4, BusStopId = 1, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 52, 0, 0) },
                        new { Id = 5, BusStopId = 1, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 47, 0, 0) },
                        new { Id = 6, BusStopId = 2, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 13, 0, 0) },
                        new { Id = 7, BusStopId = 2, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 9, 0, 0) },
                        new { Id = 8, BusStopId = 2, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 32, 0, 0) },
                        new { Id = 9, BusStopId = 2, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 16, 0, 0) },
                        new { Id = 10, BusStopId = 2, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 43, 0, 0) },
                        new { Id = 11, BusStopId = 3, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 16, 0, 0) },
                        new { Id = 12, BusStopId = 3, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 21, 0, 0) },
                        new { Id = 13, BusStopId = 3, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 41, 0, 0) },
                        new { Id = 14, BusStopId = 3, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 38, 0, 0) },
                        new { Id = 15, BusStopId = 3, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 33, 0, 0) },
                        new { Id = 16, BusStopId = 4, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 37, 0, 0) },
                        new { Id = 17, BusStopId = 4, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 45, 0, 0) },
                        new { Id = 18, BusStopId = 4, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 51, 0, 0) },
                        new { Id = 19, BusStopId = 4, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 31, 0, 0) },
                        new { Id = 20, BusStopId = 4, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 43, 0, 0) },
                        new { Id = 21, BusStopId = 5, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 46, 0, 0) },
                        new { Id = 22, BusStopId = 5, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 57, 0, 0) },
                        new { Id = 23, BusStopId = 5, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 8, 0, 0) },
                        new { Id = 24, BusStopId = 5, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 38, 0, 0) },
                        new { Id = 25, BusStopId = 5, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 13, 0, 0) },
                        new { Id = 26, BusStopId = 6, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 53, 0, 0) },
                        new { Id = 27, BusStopId = 6, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 51, 0, 0) },
                        new { Id = 28, BusStopId = 6, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 10, 0, 0) },
                        new { Id = 29, BusStopId = 6, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 14, 0, 0) },
                        new { Id = 30, BusStopId = 6, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 55, 0, 0) },
                        new { Id = 31, BusStopId = 7, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 13, 0, 0) },
                        new { Id = 32, BusStopId = 7, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 6, 0, 0) },
                        new { Id = 33, BusStopId = 7, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 53, 0, 0) },
                        new { Id = 34, BusStopId = 7, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 21, 0, 0) },
                        new { Id = 35, BusStopId = 7, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 18, 0, 0) },
                        new { Id = 36, BusStopId = 8, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 12, 0, 0) },
                        new { Id = 37, BusStopId = 8, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 7, 0, 0) },
                        new { Id = 38, BusStopId = 8, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 24, 0, 0) },
                        new { Id = 39, BusStopId = 8, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 28, 0, 0) },
                        new { Id = 40, BusStopId = 8, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 21, 0, 0) },
                        new { Id = 41, BusStopId = 9, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 14, 0, 0) },
                        new { Id = 42, BusStopId = 9, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 18, 0, 0) },
                        new { Id = 43, BusStopId = 9, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 21, 0, 0) },
                        new { Id = 44, BusStopId = 9, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 13, 0, 0) },
                        new { Id = 45, BusStopId = 9, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 38, 0, 0) },
                        new { Id = 46, BusStopId = 10, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 33, 0, 0) },
                        new { Id = 47, BusStopId = 10, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 27, 0, 0) },
                        new { Id = 48, BusStopId = 10, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 17, 0, 0) },
                        new { Id = 49, BusStopId = 10, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 46, 0, 0) },
                        new { Id = 50, BusStopId = 10, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 51, 0, 0) },
                        new { Id = 51, BusStopId = 11, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 46, 0, 0) },
                        new { Id = 52, BusStopId = 11, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 38, 0, 0) },
                        new { Id = 53, BusStopId = 11, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 31, 0, 0) },
                        new { Id = 54, BusStopId = 11, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 53, 0, 0) },
                        new { Id = 55, BusStopId = 11, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 58, 0, 0) },
                        new { Id = 56, BusStopId = 12, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 7, 0, 0) },
                        new { Id = 57, BusStopId = 12, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 12, 0, 0) },
                        new { Id = 58, BusStopId = 12, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 51, 0, 0) },
                        new { Id = 59, BusStopId = 12, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 46, 0, 0) },
                        new { Id = 60, BusStopId = 12, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 9, 0, 0) },
                        new { Id = 61, BusStopId = 13, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 7, 0, 0) },
                        new { Id = 62, BusStopId = 13, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 2, 0, 0) },
                        new { Id = 63, BusStopId = 13, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 55, 0, 0) },
                        new { Id = 64, BusStopId = 13, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 10, 47, 0, 0) },
                        new { Id = 65, BusStopId = 13, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 19, 0, 0) },
                        new { Id = 66, BusStopId = 14, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 18, 0, 0) },
                        new { Id = 67, BusStopId = 14, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 14, 0, 0) },
                        new { Id = 68, BusStopId = 14, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 8, 0, 0) },
                        new { Id = 69, BusStopId = 14, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 23, 0, 0) },
                        new { Id = 70, BusStopId = 14, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 26, 0, 0) },
                        new { Id = 71, BusStopId = 15, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 21, 0, 0) },
                        new { Id = 72, BusStopId = 15, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 16, 0, 0) },
                        new { Id = 73, BusStopId = 15, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 13, 0, 0) },
                        new { Id = 74, BusStopId = 15, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 32, 0, 0) },
                        new { Id = 75, BusStopId = 15, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 37, 0, 0) },
                        new { Id = 76, BusStopId = 16, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 38, 0, 0) },
                        new { Id = 77, BusStopId = 16, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 35, 0, 0) },
                        new { Id = 78, BusStopId = 16, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 31, 0, 0) },
                        new { Id = 79, BusStopId = 16, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 43, 0, 0) },
                        new { Id = 80, BusStopId = 16, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 44, 0, 0) },
                        new { Id = 81, BusStopId = 17, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 47, 0, 0) },
                        new { Id = 82, BusStopId = 17, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 45, 0, 0) },
                        new { Id = 83, BusStopId = 17, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 52, 0, 0) },
                        new { Id = 84, BusStopId = 17, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 57, 0, 0) },
                        new { Id = 85, BusStopId = 17, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 0, 0, 0) },
                        new { Id = 86, BusStopId = 18, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 45, 0, 0) },
                        new { Id = 87, BusStopId = 18, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 48, 0, 0) },
                        new { Id = 88, BusStopId = 18, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 11, 54, 0, 0) },
                        new { Id = 89, BusStopId = 18, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 2, 0, 0) },
                        new { Id = 90, BusStopId = 18, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 8, 0, 0) },
                        new { Id = 91, BusStopId = 19, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 2, 0, 0) },
                        new { Id = 92, BusStopId = 19, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 8, 0, 0) },
                        new { Id = 93, BusStopId = 19, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 12, 0, 0) },
                        new { Id = 94, BusStopId = 19, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 15, 0, 0) },
                        new { Id = 95, BusStopId = 19, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 10, 0, 0) },
                        new { Id = 96, BusStopId = 20, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 17, 0, 0) },
                        new { Id = 97, BusStopId = 20, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 14, 0, 0) },
                        new { Id = 98, BusStopId = 20, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 21, 0, 0) },
                        new { Id = 99, BusStopId = 20, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 25, 0, 0) },
                        new { Id = 100, BusStopId = 20, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 27, 0, 0) },
                        new { Id = 101, BusStopId = 21, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 19, 0, 0) },
                        new { Id = 102, BusStopId = 21, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 22, 0, 0) },
                        new { Id = 103, BusStopId = 21, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 28, 0, 0) },
                        new { Id = 104, BusStopId = 21, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 32, 0, 0) },
                        new { Id = 105, BusStopId = 21, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 37, 0, 0) },
                        new { Id = 106, BusStopId = 22, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 37, 0, 0) },
                        new { Id = 107, BusStopId = 22, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 39, 0, 0) },
                        new { Id = 108, BusStopId = 22, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 41, 0, 0) },
                        new { Id = 109, BusStopId = 22, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 46, 0, 0) },
                        new { Id = 110, BusStopId = 22, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 12, 51, 0, 0) },
                        new { Id = 111, BusStopId = 23, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 6, 0, 0) },
                        new { Id = 112, BusStopId = 23, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 10, 0, 0) },
                        new { Id = 113, BusStopId = 23, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 7, 56, 0, 0) },
                        new { Id = 114, BusStopId = 23, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 7, 51, 0, 0) },
                        new { Id = 115, BusStopId = 23, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 4, 0, 0) },
                        new { Id = 116, BusStopId = 24, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 7, 0, 0) },
                        new { Id = 117, BusStopId = 24, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 6, 0, 0) },
                        new { Id = 118, BusStopId = 24, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 2, 0, 0) },
                        new { Id = 119, BusStopId = 24, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 12, 0, 0) },
                        new { Id = 120, BusStopId = 24, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 14, 0, 0) },
                        new { Id = 121, BusStopId = 25, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 17, 0, 0) },
                        new { Id = 122, BusStopId = 25, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 15, 0, 0) },
                        new { Id = 123, BusStopId = 25, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 21, 0, 0) },
                        new { Id = 124, BusStopId = 25, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 24, 0, 0) },
                        new { Id = 125, BusStopId = 25, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 27, 0, 0) },
                        new { Id = 126, BusStopId = 26, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 26, 0, 0) },
                        new { Id = 127, BusStopId = 26, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 28, 0, 0) },
                        new { Id = 128, BusStopId = 26, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 32, 0, 0) },
                        new { Id = 129, BusStopId = 26, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 35, 0, 0) },
                        new { Id = 130, BusStopId = 26, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 38, 0, 0) },
                        new { Id = 131, BusStopId = 27, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 32, 0, 0) },
                        new { Id = 132, BusStopId = 27, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 37, 0, 0) },
                        new { Id = 133, BusStopId = 27, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 41, 0, 0) },
                        new { Id = 134, BusStopId = 27, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 45, 0, 0) },
                        new { Id = 135, BusStopId = 27, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 48, 0, 0) },
                        new { Id = 136, BusStopId = 28, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 46, 0, 0) },
                        new { Id = 137, BusStopId = 28, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 50, 0, 0) },
                        new { Id = 138, BusStopId = 28, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 54, 0, 0) },
                        new { Id = 139, BusStopId = 28, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 58, 0, 0) },
                        new { Id = 140, BusStopId = 28, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 8, 0, 0) },
                        new { Id = 141, BusStopId = 29, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 51, 0, 0) },
                        new { Id = 142, BusStopId = 29, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 8, 59, 0, 0) },
                        new { Id = 143, BusStopId = 29, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 3, 0, 0) },
                        new { Id = 144, BusStopId = 29, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 12, 0, 0) },
                        new { Id = 145, BusStopId = 29, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 7, 0, 0) },
                        new { Id = 146, BusStopId = 30, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 4, 0, 0) },
                        new { Id = 147, BusStopId = 30, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 8, 0, 0) },
                        new { Id = 148, BusStopId = 30, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 11, 0, 0) },
                        new { Id = 149, BusStopId = 30, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 15, 0, 0) },
                        new { Id = 150, BusStopId = 30, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 17, 0, 0) },
                        new { Id = 151, BusStopId = 31, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 14, 0, 0) },
                        new { Id = 152, BusStopId = 31, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 11, 0, 0) },
                        new { Id = 153, BusStopId = 31, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 23, 0, 0) },
                        new { Id = 154, BusStopId = 31, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 28, 0, 0) },
                        new { Id = 155, BusStopId = 31, Date = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Hour = new TimeSpan(0, 9, 39, 0, 0) }
                    );
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new { Id = 1, Name = "Nowex Transport" },
                        new { Id = 2, Name = "Kolos" }
                    );
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.CarrierQueued", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDatetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("FORMAT(GetDate(), 'yyyy-MM-dd')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NegativeVotes")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("PositiveVotes")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("VotingEndedDateTime");

                    b.Property<DateTime?>("VotingStartedDatetime");

                    b.HasKey("Id");

                    b.ToTable("CarriersQueued");
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId");

                    b.Property<string>("DayOfTheWeek");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("Routes");

                    b.HasData(
                        new { Id = 1, CarrierId = 1, DayOfTheWeek = "1,2,3", Name = "Gorlice - Rzeszów" },
                        new { Id = 2, CarrierId = 1, DayOfTheWeek = "1,2,3", Name = "Rzeszów - Gorlice" },
                        new { Id = 3, CarrierId = 2, DayOfTheWeek = "2", Name = "Frysztak - Rzeszów" }
                    );
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteDelay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("RouteId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteDelays");
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteQueued", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId");

                    b.Property<int?>("CarrierQueuedId");

                    b.Property<DateTime>("CreatedDatetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("FORMAT(GetDate(), 'yyyy-MM-dd')");

                    b.Property<string>("DayOfTheWeek");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NegativeVotes")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("PositiveVotes")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("VotingEndedDateTime");

                    b.Property<DateTime?>("VotingStartedDatetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierQueuedId");

                    b.ToTable("RoutesQueued");
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("FORMAT(GetDate(), 'yyyy-MM-dd')");

                    b.Property<string>("Description");

                    b.Property<int>("RouteId");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteReports");
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStop", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.Route", "Route")
                        .WithMany("BusStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStopQueued", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.RouteQueued", "RouteQueued")
                        .WithMany("BusStopsQueued")
                        .HasForeignKey("RouteQueuedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.BusStopTrace", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.BusStop", "BusStop")
                        .WithMany("BusStopTraces")
                        .HasForeignKey("BusStopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.Route", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.Carrier", "Carrier")
                        .WithMany("Routes")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteDelay", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteQueued", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.CarrierQueued", "CarrierQueued")
                        .WithMany("RoutesQueued")
                        .HasForeignKey("CarrierQueuedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusMap.WebApi.DatabaseModels.RouteReport", b =>
                {
                    b.HasOne("BusMap.WebApi.DatabaseModels.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
